### ISSUE TITLE
crash during world load

### ISSUE THREAD

**Issue by jackg2527** [Commoble/stucturespawnloader#1]
Hi there, very happy to see your mod updated. Unfortunately crashed as soon as world started loading. Crash report attached, here is crashy link in case helpful: https://crashy.net/ZLuu8ekNs4GMdEHcZF6v    

1.18.1, forge 39.0.5 and ~120 mods.

Added:
- workshopsofdoom-1.18.1-2.0.0.1.jar
- structure_spawn_loader-1.18.1-1.0.0.0.jar
- looot-1.18-1.1.0.0.jar

Mods loaded ok, but crashed right after I clicked on world save.

Any help would be much appreciated.

Thank you
[crash-2021-12-19_20.53.03-server.txt](https://github.com/Commoble/stucturespawnloader/files/7742741/crash-2021-12-19_20.53.03-server.txt)
!

**Comment by Commoble** [comment]
I found the issue and it's a problem specific to Workshops of Doom rather than Structure Spawn Loader, it'll take a day to fix but I'll be working on it

https://github.com/Commoble/workshopsofdoom/issues/2

**Comment by jackg2527** [comment]
Thanks for the quick reply and fix! Just tried it and all good. And oops meant to post this on WoD. Cheers
